/*
**	$Id$
**	Generated by IDLTool 53.24
**	Do not edit
**
**	AutoInit stub for powerpacker
**
**	Copyright (c) 2010 Hyperion Entertainment CVBA.
**	All Rights Reserved.
*/

#include <exec/types.h>
#include <libraries/powerpacker.h>

#include <interfaces/powerpacker.h>
#include <proto/exec.h>
#include <proto/dos.h>
#include <stdlib.h>

struct PowerPackerIFace * IPowerPacker = NULL;
static struct Library * __PowerPackerBase = NULL;
static struct PowerPackerIFace * __IPowerPacker = NULL;

/****************************************************************************/

extern struct Library * PowerPackerBase;

/****************************************************************************/

void powerpacker_main_constructor(void)
{
    if (IPowerPacker != NULL)
    {
        return; /* Someone was quicker */
    }
    if (PowerPackerBase == NULL) /* Library base is NULL, we need to open it */
    {
        /* We were called before the base constructor.
         * This means we will be called _after_ the base destructor.
         * So we cant drop the interface _after_ closing the last library base,
         * we just open the library here which ensures that.
         */
        __PowerPackerBase = PowerPackerBase = IExec->OpenLibrary("powerpacker.library", 0);
        if (PowerPackerBase == NULL)
        {
            IDOS->PutErrStr("ERROR: Failed to open 'powerpacker.library'.\n");
            abort();
        }
    }

    __IPowerPacker = IPowerPacker = (struct PowerPackerIFace *)IExec->GetInterface((struct Library *)PowerPackerBase, "main", 1, NULL);
    if (IPowerPacker == NULL)
    {
        IDOS->PutErrStr("ERROR: Failed to get 'main' V1 interface for 'powerpacker.library'.\n");
        abort();
    }
}
__attribute__((section(".ctors.zzzy"))) static void
(*powerpacker_main_constructor_ptr)(void) USED = powerpacker_main_constructor;

/****************************************************************************/

void powerpacker_main_destructor(void)
{
    if (__IPowerPacker)
    {
        IExec->DropInterface ((struct Interface *)__IPowerPacker);
    }
    if (__PowerPackerBase)
    {
        IExec->CloseLibrary(__PowerPackerBase);
    }
}
__attribute__((section(".dtors.zzzy"))) static void
(*powerpacker_main_destructor_ptr)(void) USED = powerpacker_main_destructor;

/****************************************************************************/

